name: Self Hosted Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Runner
        run: |
          echo "Hello from Self Hosted Runner"
          hostname